using System.Collections.Generic;

namespace RoR2MusicNotification
{
    internal class Data
    {
        public static Dictionary<string, string> trackNames = new Dictionary<string, string>()
        {
            {"muBossfightDLC1_10", "Having Fallen, It Was Blood"},
            {"muBossfightDLC1_12", "A Boat Made from a Sheet of Newspaper"},
            {"muEscape", "Escape (Unnamed Track)"},
            {"muFULLSong02", "Into the Doldrums"},
            {"muFULLSong06", "Nocturnal Emission"},
            {"muFULLSong07", "Evapotranspiration"},
            {"muFULLSong18", "Disdrometer"},
            {"muFULLSong19", "Terra Pluviam"},
            {"muGameplayBase_09", "They Might As Well Be Dead"},
            {"muGameplayDLC1_01", "Once in a Lullaby"},
            {"muGameplayDLC1_03", "Out of Whose Womb Came the Ice?"},
            {"muGameplayDLC1_06", "Who Can Fathom the Soundless Depths?"},
            {"muGameplayDLC1_08", "A Placid Island of Ignorance"},
            {"muIntroCutscene", "Through a Cloud, Darkly"},
            {"muLogbook", "The Dehydration of Risk of Rain 2"},
            {"muMainEndingFull", "Lacrimosum"},
            {"muMainEndingOutroA", "Lacrimosum"},
            {"muMainEndingOutroB", "Lacrimosum"},
            {"muMenu", "Risk of Rain 2"},
            {"muMenuDLC1", "Prelude in D flat major"},
            {"muNone", ""},
            {"muRaidfightDLC1_07", "The Face of the Deep"},
            {"muSong04", "Parjanya"},
            {"muSong05", "Thermodynamic Equilibrium"},
            {"muSong08", "A Glacier Eventually Farts (And Don't You Listen to the Song of Life)"},
            {"muSong13", "The Raindrop that Fell to the Sky"},
            {"muSong14", "The Rain Formerly Known as Purple"},
            {"muSong16", "Hydrophobia"},
            {"muSong21", "Petrichor V"},
            {"muSong22", "Köppen As Fuck"},
            {"muSong23", "Antarctic Oscillation"},
            {"muSong24", "...con lentitud poderosa"},
            {"muSong25", "You're Gonna Need A Bigger Ukulele"},
            {"muSong_Habitat", "Om Mani Padme Hum, part II"},
            //{"muSong_Habitat", "Oṃ Maṇi Padme Hūṃ, part II"},
            {"muSong_HelminthBoss", "Tlalocan"},
            //{"muSong_HelminthBoss", "Tlālōcān"},
            {"muSong_HelminthRoost", "屋根の漏り (Yane No Mori)"},
            {"muSong_Lakes&HabitatBoss", "A Tempestuous Noise of Thunder and Lightning Heard"},
            {"muSong_LakesGameplay", "It Can't Rain All the Time"},
            {"muSong_LemurianTemple", "Om Mani Padme Hum, part III"},
            //{"muSong_LemurianTemple", "Oṃ Maṇi Padme Hūṃ, part III"},
            {"muSong_LemurianTempleBoss", "Forgot the Cry of Gulls"},
            {"muSong_Meridian", "Om Mani Padme Hum, part I"},
            //{"muSong_Meridian", "Oṃ Maṇi Padme Hūṃ, part I"},
            {"muSong_MeridianFSB", "Om Mani Padme Hum, part I"},
            //{"muSong_MeridianFSB", "Oṃ Maṇi Padme Hūṃ, part I"},
            {"muSong_Village", "I Should Build the Man a Statue"},
            {"muSong_VillageBoss", "Forgot the Cry of Gulls"},

            {"muGameplayDLC3_01_SH_Map", "Mistery"},
            {"muGameplayDLC3_02_P_Map", "Swamplified Mizzle"},
            {"muGameplayDLC3_03_IA_Map", "Mine Your Drone Business!"},
            {"muGameplayDLC3_04_RC_Map", "Reign of hrisC"},
            {"muGameplayDLC3_05_CE_Map", "Even Strong Swimmers Can Drone"},
            {"muGameplayDLC3_06_CC_Map", "We’ll Rain Together"},
            {"muGameplayDLC3_07_RC_Boss", "A Torrent That Can't Be Downloaded"},
            {"muGameplayDLC3_08_RMX_SolHeart_Boss", "Heav’n Flies Before the Machine Soul (BT)"},
            {"muGameplayDLC3_08_SH_Boss", "Deluge ional"},
        };

        public static Dictionary<string, string> trackAuthors = new Dictionary<string, string>()
        {
            {"muBossfightDLC1_10", "Chris Christodoulou"},
            {"muBossfightDLC1_12", "Chris Christodoulou"},
            {"muEscape", "Chris Christodoulou"},
            {"muFULLSong02", "Chris Christodoulou"},
            {"muFULLSong06", "Chris Christodoulou"},
            {"muFULLSong07", "Chris Christodoulou"},
            {"muFULLSong18", "Chris Christodoulou"},
            {"muFULLSong19", "Chris Christodoulou"},
            {"muGameplayBase_09", "Chris Christodoulou"},
            {"muGameplayDLC1_01", "Chris Christodoulou"},
            {"muGameplayDLC1_03", "Chris Christodoulou"},
            {"muGameplayDLC1_06", "Chris Christodoulou"},
            {"muGameplayDLC1_08", "Chris Christodoulou"},
            {"muGameplayDLC3_01_SH_Map", "Stavros Markonis"},
            {"muGameplayDLC3_02_P_Map", "Stavros Markonis"},
            {"muGameplayDLC3_03_IA_Map", "Stavros Markonis"},
            {"muGameplayDLC3_04_RC_Map", "Stavros Markonis"},
            {"muGameplayDLC3_05_CE_Map", "Stavros Markonis"},
            {"muGameplayDLC3_06_CC_Map", "Stavros Markonis"},
            {"muGameplayDLC3_07_RC_Boss", "Stavros Markonis"},
            {"muGameplayDLC3_08_RMX_SolHeart_Boss", "Stavros Markonis"},
            {"muGameplayDLC3_08_SH_Boss", "Stavros Markonis"},
            {"muIntroCutscene", "Chris Christodoulou"},
            {"muLogbook", "Chris Christodoulou"},
            {"muMainEndingFull", "Chris Christodoulou"},
            {"muMainEndingOutroA", "Chris Christodoulou"},
            {"muMainEndingOutroB", "Chris Christodoulou"},
            {"muMenu", "Chris Christodoulou"},
            {"muMenuDLC1", "Chris Christodoulou"},
            {"muNone", "Chris Christodoulou"},
            {"muRaidfightDLC1_07", "Chris Christodoulou"},
            {"muSong_Habitat", "Chris Christodoulou"},
            {"muSong_HelminthBoss", "Chris Christodoulou"},
            {"muSong_HelminthRoost", "Chris Christodoulou"},
            {"muSong_Lakes&HabitatBoss", "Chris Christodoulou"},
            {"muSong_LakesGameplay", "Chris Christodoulou"},
            {"muSong_LemurianTemple", "Chris Christodoulou"},
            {"muSong_LemurianTempleBoss", "Chris Christodoulou"},
            {"muSong_Meridian", "Chris Christodoulou"},
            {"muSong_MeridianFSB", "Chris Christodoulou"},
            {"muSong_Village", "Stavros Markonis"},
            {"muSong_VillageBoss", "Chris Christodoulou"},
            {"muSong04", "Chris Christodoulou"},
            {"muSong05", "Chris Christodoulou"},
            {"muSong08", "Chris Christodoulou"},
            {"muSong13", "Chris Christodoulou"},
            {"muSong14", "Chris Christodoulou"},
            {"muSong16", "Chris Christodoulou"},
            {"muSong21", "Chris Christodoulou"},
            {"muSong22", "Chris Christodoulou"},
            {"muSong23", "Chris Christodoulou"},
            {"muSong24", "Chris Christodoulou"},
            {"muSong25", "Chris Christodoulou"},
        };
    }
}
